from pptx import Presentation
from pptx.util import Pt

class PPTXService:

    @staticmethod
    def create_pptx(title: str, slides: list, output_path: str) -> str:
        prs = Presentation()

        # Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        slide.shapes.title.text = title
        slide.placeholders[1].text = "Generated by AI Slide Generator"

        # Content Slides
        for s in slides:
            layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(layout)
            slide.shapes.title.text = s.title

            tf = slide.placeholders[1].text_frame
            for bp in s.bullets:
                p = tf.add_paragraph()
                p.text = bp
                p.font.size = Pt(18)
                p.level = 0

        prs.save(output_path)
        return output_path